# Generated by Django 3.2.5 on 2021-07-29 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testjobs', '0002_bangalorejobs_punejobs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hydjobs',
            new_name='Hydjobs1',
        ),
    ]
