# Generated by Django 3.2.5 on 2021-07-29 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testjobs', '0003_rename_hydjobs_hydjobs1'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Hydjobs1',
            new_name='Hyderabadjobs',
        ),
    ]
